[package]
name        = "just"
version     = "0.3.2"
description = "ðŸ¤– Just a command runner"
authors     = ["Casey Rodarmor <casey@rodarmor.com>"]
license     = "WTFPL OR MIT OR Apache-2.0"
homepage    = "https://github.com/casey/just"
readme      = "README.asc"

[dependencies]
ansi_term     = "^0.9.0"
atty          = "^0.2.1"
brev          = "^0.1.6"
clap          = "^2.0.0"
edit-distance = "^2.0.0"
itertools     = "^0.6.2"
lazy_static   = "^0.2.1"
libc          = "^0.2.21"
regex         = "^0.2.2"
tempdir       = "^0.3.5"
unicode-width = "^0.1.3"
